-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgrqv1NxLeZ/Tyo9LCF9+k3KTnFQGTvCkGHDijb/A8baugCgYIKoZIzj0DAQehRANCAAS2AClj2jK+DslDXUAnXQgyCnoVq7RhDBYIO+g64FJ1CzrohSYRqyOorbu2Ru1uP48exMSgZJKgZfSgFVw7i1Jv
-----END PRIVATE KEY-----